use crate::{
    core::{
        collision_filter::CollisionFilter, common::ShapeType,
        constraint_impulse::ConstraintImpulse, force::Force, position::Position, render::Render,
        velocity::Velocity,
    },
    geometry::{bounds::Bounds, vector::Vector},
};

use super::body::Body;

pub enum BodyOption {
    Angle(f64),
    AnglePrev(f64),
    AngularSpeed(f64),
    AngularVelocity(f64),
    Area(f64),
    Axes(Vec<Vector>),
    Bounds(Bounds),
    Chamfer(Vec<Vector>),
    CircleRadius(f64),
    CollisionFilter(CollisionFilter),
    ConstraintImpulse(ConstraintImpulse),
    DeltaTime(f64),
    Density(f64),
    //Events
    Force(Force),
    Friction(f64),
    FrictionAir(f64),
    FrictionStatic(f64),
    Inertia(f64),
    IsSensor(bool),
    IsSleeping(bool),
    IsStatic(bool),
    Mass(f64),
    Motion(f64),
    Original(Body),
    Parent(Body),
    Parts(Vec<Body>),
    //Plugin:
    Position(Position),
    PositionImpulse(Position),
    PositionPrev(Position),
    Render(Render),
    Resitution(f64),
    ShapeType(ShapeType),
    SleepThreshold(u32),
    Slop(f64),
    Speed(f64),
    TimeScale(u16),
    Torque(f64),
    TotalContracts(u32),
    Velocity(Velocity),
    Vertices(Vec<Vector>),
}
